create table if not exists loan_intelligent_quota_list_value_ref_auth(
authorizer_id bigint not null,
loan_iq_source_system_value_cat_code varchar(255) null,
loan_iq_source_system_value_sub_cat_code varchar(255) null,
code_owner varchar(255) null,
code_verifier varchar(255) null,
code_completion_team varchar(255) null,
email_group varchar(255) null,
ref_data_id bigint null,
sequence Integer null,
modular_data varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint loan_intelligent_quota_list_value_ref_auth_pk primary key(authorizer_id));